export const PATH_PARAMS = [
  "pretrained_model_name_or_path",
  "train_data_dir",
  "reg_data_dir",
  "output_dir",
  "network_weights",
  "conditioning_data_dir",
  "controlnet_model_name_or_path",
  "weights",
  "vae",
  "text_encoder",
  "byt5",
  "qwen3",
  "llm_adapter_path",
  "t5_tokenizer_path",
  "ae",
  "clip_l",
  "clip_g",
  "t5xxl",
  "gemma2",
];

export const FLOAT_PARAMS = [
  "learning_rate",
  "unet_lr",
  "text_encoder_lr",
  "learning_rate_te",
  "learning_rate_te1",
  "learning_rate_te2",
  "learning_rate_te3",
  "sigmoid_scale",
  "guidance_scale",
  "training_shift",
  "control_net_lr",
  "self_attn_lr",
  "cross_attn_lr",
  "mlp_lr",
  "mod_lr",
  "llm_adapter_lr",
];

export const NEED_DELETE_PARAMS = [
  "lycoris_algo",
  "conv_dim",
  "conv_alpha",
  "dropout",
  "dylora_unit",
  "lokr_factor",
  "train_norm",
  "down_lr_weight",
  "mid_lr_weight",
  "up_lr_weight",
  "block_lr_zero_threshold",
  "enable_block_weights",
  "enable_preview",
  "network_args_custom",
  "optimizer_args_custom",
  "enable_base_weight",
  "prodigy_d0",
  "prodigy_d_coef",
  "ui_custom_params",
];

export const TEST_NONE_PARAMS = [
  "vae",
  "reg_data_dir",
  "network_weights",
  "conditioning_data_dir",
  "controlnet_model_name_or_path",
  "weights",
  "init_word",
  "text_encoder",
  "byt5",
  "qwen3",
  "llm_adapter_path",
  "t5_tokenizer_path",
  "ae",
  "clip_l",
  "clip_g",
  "t5xxl",
  "gemma2",
  "noise_offset",
  "multires_noise_iterations",
  "multires_noise_discount",
  "caption_dropout_rate",
  "network_dropout",
  "scale_weight_norms",
  "gpu_ids",
];

export const SD12_EXCLUSIVE_PARAMS = [
  "v2",
  "v_parameterization",
  "scale_v_pred_loss_like_noise_pred",
  "clip_skip",
  "learning_rate_te",
  "stop_text_encoder_training",
];

export const SDXL_EXCLUSIVE_PARAMS = ["learning_rate_te1", "learning_rate_te2"];

export const CONFLICT_PARAMS = [
  ["cache_text_encoder_outputs", "shuffle_caption"],
  ["noise_offset", "multires_noise_iterations"],
  ["cache_latents", "color_aug"],
  ["cache_latents", "random_crop"],
] as const;

export const NETWORK_ARG_REVERSE_MAP: Record<string, string> = {
  algo: "lycoris_algo",
  unit: "dylora_unit",
  factor: "lokr_factor",
};

export const NETWORK_ARG_DIRECT_KEYS = new Set([
  "conv_dim",
  "conv_alpha",
  "dropout",
  "down_lr_weight",
  "mid_lr_weight",
  "up_lr_weight",
  "block_lr_zero_threshold",
]);

export const OPTIMIZER_ARG_IGNORED_KEYS = new Set([
  "decouple",
  "weight_decay",
  "use_bias_correction",
  "safeguard_warmup",
]);

export const ARRAY_TEXTAREA_KEYS = new Set(["base_weights", "base_weights_multiplier"]);

export const BASIC_LORA_DEFAULTS: Record<string, unknown> = {
  pretrained_model_name_or_path: "./sd-models/model.safetensors",
  train_data_dir: "./train/aki",
  resolution: "512,512",
  enable_bucket: true,
  min_bucket_reso: 256,
  max_bucket_reso: 1024,
  output_name: "aki",
  output_dir: "./output",
  save_model_as: "safetensors",
  save_every_n_epochs: 2,
  max_train_epochs: 10,
  train_batch_size: 1,
  network_train_unet_only: false,
  network_train_text_encoder_only: false,
  learning_rate: 1e-4,
  unet_lr: 1e-4,
  text_encoder_lr: 1e-5,
  lr_scheduler: "cosine_with_restarts",
  optimizer_type: "AdamW8bit",
  lr_scheduler_num_cycles: 1,
  network_module: "networks.lora",
  network_dim: 32,
  network_alpha: 32,
  logging_dir: "./logs",
  caption_extension: ".txt",
  shuffle_caption: true,
  keep_tokens: 0,
  max_token_length: 255,
  seed: 1337,
  prior_loss_weight: 1,
  clip_skip: 2,
  mixed_precision: "fp16",
  save_precision: "fp16",
  xformers: true,
  cache_latents: true,
  persistent_data_loader_workers: true,
};
