export type RouteRecord = {
  route: string;
  title: string;
  section: "core" | "training" | "tools" | "system";
  status: "legacy-dist" | "migrate-first";
  notes: string;
  schemaHints?: string[];
};

export const routeInventory: RouteRecord[] = [
  {
    route: "index.html",
    title: "SD-reScripts 首页",
    section: "core",
    status: "migrate-first",
    notes: "首页与主导航入口，也是最适合优先源码化的页面之一。",
  },
  {
    route: "lora/index.html",
    title: "LoRA 训练总览",
    section: "training",
    status: "migrate-first",
    notes: "训练模型选择的总入口页面。",
    schemaHints: ["shared"],
  },
  {
    route: "lora/sdxl.html",
    title: "SDXL LoRA 训练",
    section: "training",
    status: "migrate-first",
    notes: "当前最核心、最常用的训练页面。",
    schemaHints: ["sdxl-lora", "shared"],
  },
  {
    route: "lora/flux.html",
    title: "Flux LoRA 训练",
    section: "training",
    status: "migrate-first",
    notes: "已经由共享训练桥在源码版中镜像接入。",
    schemaHints: ["flux-lora", "shared"],
  },
  {
    route: "lora/sd3.html",
    title: "SD3 训练",
    section: "training",
    status: "migrate-first",
    notes: "已经由共享训练桥在源码版中镜像接入。",
    schemaHints: ["sd3-lora", "shared"],
  },
  {
    route: "lora/controlnet.html",
    title: "SD ControlNet 训练",
    section: "training",
    status: "migrate-first",
    notes: "已经由共享训练桥在源码版中镜像接入。",
    schemaHints: ["sd-controlnet", "shared"],
  },
  {
    route: "lora/sdxl-controlnet.html",
    title: "SDXL ControlNet 训练",
    section: "training",
    status: "migrate-first",
    notes: "已经由共享训练桥在源码版中镜像接入。",
    schemaHints: ["sdxl-controlnet", "shared"],
  },
  {
    route: "lora/sdxl-lllite.html",
    title: "SDXL LLLite 训练",
    section: "training",
    status: "migrate-first",
    notes: "用于 SDXL 特殊条件训练的页面，已经接入源码版共享训练桥。",
    schemaHints: ["sdxl-controlnet-lllite", "shared"],
  },
  {
    route: "lora/flux-controlnet.html",
    title: "Flux ControlNet 训练",
    section: "training",
    status: "migrate-first",
    notes: "已经由共享训练桥在源码版中镜像接入。",
    schemaHints: ["flux-controlnet", "shared"],
  },
  {
    route: "lora/basic.html",
    title: "LoRA 新手模式",
    section: "training",
    status: "legacy-dist",
    notes: "旧版保留的新手向训练入口。",
    schemaHints: ["lora-basic", "shared"],
  },
  {
    route: "lora/master.html",
    title: "LoRA 专家模式",
    section: "training",
    status: "legacy-dist",
    notes: "旧版保留的专家向训练入口。",
    schemaHints: ["lora-master", "shared"],
  },
  {
    route: "lora/params.html",
    title: "训练参数说明",
    section: "training",
    status: "migrate-first",
    notes: "以说明文档为主，比较适合优先重建。",
  },
  {
    route: "lora/tools.html",
    title: "LoRA 工具页",
    section: "tools",
    status: "migrate-first",
    notes: "用于合并、缩放、打标和转换等工具流程的入口页。",
  },
  {
    route: "dreambooth/index.html",
    title: "Dreambooth 训练",
    section: "training",
    status: "migrate-first",
    notes: "Dreambooth 与 SDXL 全量微调入口，已经接入源码版共享训练桥。",
    schemaHints: ["dreambooth", "shared"],
  },
  {
    route: "tagger.html",
    title: "Tagger 标注工具",
    section: "tools",
    status: "migrate-first",
    notes: "独立的标签生成入口，会直接调用后端 API。",
    schemaHints: ["tagger"],
  },
  {
    route: "tageditor.html",
    title: "标签编辑器包装页",
    section: "tools",
    status: "migrate-first",
    notes: "负责显示进度与失败状态的包装页，适合优先源码化重写。",
  },
  {
    route: "task.html",
    title: "任务监视页",
    section: "system",
    status: "migrate-first",
    notes: "由 /api/tasks 驱动的任务状态页。",
  },
  {
    route: "tensorboard.html",
    title: "TensorBoard 包装页",
    section: "system",
    status: "migrate-first",
    notes: "轻量包装页，比表单型训练页更适合先迁移。",
  },
  {
    route: "other/settings.html",
    title: "设置页",
    section: "system",
    status: "migrate-first",
    notes: "偏静态的系统页面，适合较早完成源码重建。",
  },
  {
    route: "other/about.html",
    title: "关于页",
    section: "core",
    status: "migrate-first",
    notes: "主要承载项目信息和发布说明，是低风险迁移目标。",
  },
  {
    route: "404.html",
    title: "404 页面",
    section: "core",
    status: "legacy-dist",
    notes: "可以在主路由彻底稳定后再替换。",
  },
];
