export type RouteRecord = {
  route: string;
  title: string;
  section: "core" | "training" | "tools" | "system";
  status: "legacy-dist" | "migrate-first";
  notes: string;
  schemaHints?: string[];
};

export const routeInventory: RouteRecord[] = [
  {
    route: "index.html",
    title: "SD-reScripts | SD training UI",
    section: "core",
    status: "migrate-first",
    notes: "Landing page and main navigation entry. Good first candidate for source migration.",
  },
  {
    route: "lora/index.html",
    title: "LoRA training index",
    section: "training",
    status: "migrate-first",
    notes: "Top-level training model selector page.",
    schemaHints: ["shared"],
  },
  {
    route: "lora/sdxl.html",
    title: "SDXL LoRA training",
    section: "training",
    status: "migrate-first",
    notes: "Primary training page currently used most often.",
    schemaHints: ["sdxl-lora", "shared"],
  },
  {
    route: "lora/flux.html",
    title: "Flux LoRA training",
    section: "training",
    status: "migrate-first",
    notes: "Now mirrored by the shared source-side training bridge.",
    schemaHints: ["flux-lora", "shared"],
  },
  {
    route: "lora/sd3.html",
    title: "SD3 training",
    section: "training",
    status: "migrate-first",
    notes: "Now mirrored by the shared source-side training bridge.",
    schemaHints: ["sd3-lora", "shared"],
  },
  {
    route: "lora/controlnet.html",
    title: "SD ControlNet training",
    section: "training",
    status: "migrate-first",
    notes: "Now mirrored by the shared source-side training bridge.",
    schemaHints: ["sd-controlnet", "shared"],
  },
  {
    route: "lora/sdxl-controlnet.html",
    title: "SDXL ControlNet training",
    section: "training",
    status: "migrate-first",
    notes: "Now mirrored by the shared source-side training bridge.",
    schemaHints: ["sdxl-controlnet", "shared"],
  },
  {
    route: "lora/sdxl-lllite.html",
    title: "SDXL LLLite training",
    section: "training",
    status: "migrate-first",
    notes: "Specialized SDXL conditioning route now mirrored by the shared source-side bridge.",
    schemaHints: ["sdxl-controlnet-lllite", "shared"],
  },
  {
    route: "lora/flux-controlnet.html",
    title: "Flux ControlNet training",
    section: "training",
    status: "migrate-first",
    notes: "Now mirrored by the shared source-side training bridge.",
    schemaHints: ["flux-controlnet", "shared"],
  },
  {
    route: "lora/basic.html",
    title: "LoRA basic mode",
    section: "training",
    status: "legacy-dist",
    notes: "Legacy beginner-mode training route.",
    schemaHints: ["lora-basic", "shared"],
  },
  {
    route: "lora/master.html",
    title: "LoRA expert mode",
    section: "training",
    status: "legacy-dist",
    notes: "Legacy expert-mode training route.",
    schemaHints: ["lora-master", "shared"],
  },
  {
    route: "lora/params.html",
    title: "Training parameter reference",
    section: "training",
    status: "migrate-first",
    notes: "Mostly explanatory UI. Lower risk to recreate cleanly.",
  },
  {
    route: "lora/tools.html",
    title: "LoRA tools",
    section: "tools",
    status: "migrate-first",
    notes: "Tool launcher route for merge, resize, interrogate and conversion flows.",
  },
  {
    route: "dreambooth/index.html",
    title: "Dreambooth training",
    section: "training",
    status: "migrate-first",
    notes: "Now mirrored by the shared source-side training bridge for Dreambooth and SDXL full finetune.",
    schemaHints: ["dreambooth", "shared"],
  },
  {
    route: "tagger.html",
    title: "Tagger tool",
    section: "tools",
    status: "migrate-first",
    notes: "Standalone caption/tag generation route that talks to backend APIs.",
    schemaHints: ["tagger"],
  },
  {
    route: "tageditor.html",
    title: "Tag editor proxy page",
    section: "tools",
    status: "migrate-first",
    notes: "Wrapper page with progress/failure states. Good candidate to reimplement cleanly.",
  },
  {
    route: "task.html",
    title: "Task monitor",
    section: "system",
    status: "migrate-first",
    notes: "Task status page backed by /api/tasks.",
  },
  {
    route: "tensorboard.html",
    title: "TensorBoard proxy page",
    section: "system",
    status: "migrate-first",
    notes: "Wrapper/proxy page. Safer than schema-heavy form routes.",
  },
  {
    route: "other/settings.html",
    title: "Settings page",
    section: "system",
    status: "migrate-first",
    notes: "Static/system page that should be easy to recreate in source form.",
  },
  {
    route: "other/about.html",
    title: "About page",
    section: "core",
    status: "migrate-first",
    notes: "Mostly branding and release notes. Best low-risk migration target.",
  },
  {
    route: "404.html",
    title: "Fallback page",
    section: "core",
    status: "legacy-dist",
    notes: "Can be replaced after the main router is rebuilt.",
  },
];
